# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production domain redirects
[[redirects]]
  from = "https://hotsnow.blueroad.ee/*"
  to = "https://blueroad.ee/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://zarender.blueroad.ee/*"
  to = "https://blueroad.ee/portfolio/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Production environment configuration
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }
